// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/brand": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/signup" | "/dashboard" | "/brand";
  };
  "routes/auth.signup/route.tsx": {
    id: "routes/auth.signup";
    page: "/auth/signup";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/brand.tsx": {
    id: "routes/brand";
    page: "/brand";
  };
};