name: conformitea-dev

services:
  database:
    image: postgres:17.5-bookworm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conformitea

    volumes:
      - ../db/data:/var/lib/postgresql/data
    networks:
      - conformitea-net

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@conformitea.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: True
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
    networks:
      - conformitea-net
    ports:
      - 5050:80
    depends_on:
      - database

networks:
  conformitea-net:
