name: conformitea-dev

services:
  codespace:
    image: mcr.microsoft.com/devcontainers/go:1
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/conformitea
    volumes:
      - ..:/workspaces/conformitea:cached
    command: sleep infinity

  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conformitea
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@conformitea.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: True
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres

  hydra:
    image: oryd/hydra:v2.3.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./hydra
        target: /etc/config/hydra
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/hydra?sslmode=disable
    restart: unless-stopped
    depends_on:
      - hydra-migrate

  hydra-migrate:
    image: oryd/hydra:v2.3.0
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/hydra?sslmode=disable
    command: migrate -c /etc/config/hydra/hydra.yml sql up -e --yes
    volumes:
      - type: bind
        source: ./hydra
        target: /etc/config/hydra
    restart: on-failure
    depends_on:
      - postgres

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pg-data:
  pgadmin-data:
