name: conformitea-dev

services:
  codespace:
    image: mcr.microsoft.com/devcontainers/go:1
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/conformitea
    volumes:
      - ..:/workspaces/conformitea:cached
    command: sleep infinity

  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conformitea
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@conformitea.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: True
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  pg-data:
  pgadmin-data:
